### User Registration
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "<USERNAME>",
  "password": "<PASSWORD>"
}

### User Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "<USERNAME>",
  "password": "<PASSWORD>"
}

### Authenticated Request
GET http://localhost:3000/tasks/<userId>
Authorization: Bearer <TOKEN>

### Create New Task
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "description": "<TASK_DESCRIPTION>",
  "user": "<USER_ID>"
}

### Complete Task
PATCH http://localhost:3000/tasks/<taskId>/complete
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "completed": true,
  "completedAt": "<DATE_TIME>"
}

### Update Task
PATCH http://localhost:3000/tasks/<taskId>/update
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "description": "<UPDATED_TASK_DESCRIPTION>"
}

### Add Pomodoro
POST http://localhost:3000/tasks/<userId>/pomodoro
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "completedAt": "<DATE_TIME>"
}

### Update Pomodoro timer settings
PATCH http://localhost:3000/users/<userId>/settings
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "workMinutes": <WORK_MINUTES>,
  "shortBreakMinutes": <SHORT_BREAK_MINUTES>,
  "longBreakMinutes": <LONG_BREAK_MINUTES>
}

### Delete Task
DELETE http://localhost:3000/tasks/<taskId>
Authorization: Bearer <TOKEN>

### Delete user and all tasks
DELETE http://localhost:3000/users/<userId>
Authorization: Bearer <TOKEN>

### Get endpoints
GET http://localhost:3000/endpoints


